# fly.toml file generated for ka on 2023-01-26T20:29:02-03:00

app = "ka"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[mounts]
source="repofolder"
destination="/src/repositories"