# fly.toml file generated for kagarisoft-repo on 2023-01-27T18:41:27-03:00

app = "kagarisoft-repo"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[mounts]
  destination = "/data"
  source = "persistent"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
